# Generated by Django 5.2 on 2025-05-06 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Products.product',),
        ),
    ]
